# Generated by Django 5.2.2 on 2025-07-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessclass',
            name='trainer_image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
