# Generated by Django 5.2.2 on 2025-07-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_fitnessclass_trainer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessclass',
            name='trainer_image',
        ),
    ]
